version: "3.8"

services:
  geocoding-api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - redis-net
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - redis-net
    volumes:
      - cache:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  redis-net:
    name: redis-net

volumes:
  cache:
